name: credit-card-segmentation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - openpyxl
  - pip